var master_option_list = [
    { id: 0, name: '特性を選択してください', effect_limit: 0, parts_limit: 0, percent_flg: 0, add_flg: 0, group: 0, type: 'nodata', blade: 1, gun: 1, shield: 1, head: 1, body: 1, r_arm: 1, l_arm: 1, leg: 1, jump: 1, os: 1, assist: 1 },
    { id: 1, name: '攻撃力プラス', effect_limit: 999, parts_limit: 250, percent_flg: 0, add_flg: 0, group: 1, type: 'A', blade: 1, gun: 1, shield: 1, head: 0, body: 0, r_arm: 1, l_arm: 1, leg: 0, jump: 0, os: 0, assist: 0 },
    { id: 2, name: '長刀攻撃力アップ', effect_limit: 25, parts_limit: 15, percent_flg: 1, add_flg: 1, group: 2, type: 'A', blade: 1, gun: 0, shield: 1, head: 1, body: 1, r_arm: 1, l_arm: 1, leg: 1, jump: 1, os: 1, assist: 0 },
    { id: 3, name: '突撃砲攻撃力アップ', effect_limit: 25, parts_limit: 15, percent_flg: 1, add_flg: 1, group: 2, type: 'A', blade: 0, gun: 1, shield: 1, head: 1, body: 1, r_arm: 1, l_arm: 1, leg: 1, jump: 1, os: 1, assist: 0 },
    { id: 4, name: '格闘攻撃力アップ', effect_limit: 25, parts_limit: 15, percent_flg: 1, add_flg: 1, group: 2, type: 'A', blade: 1, gun: 1, shield: 0, head: 1, body: 1, r_arm: 1, l_arm: 1, leg: 1, jump: 1, os: 1, assist: 0 },
    { id: 5, name: '追加装甲攻撃力アップ', effect_limit: 25, parts_limit: 15, percent_flg: 1, add_flg: 1, group: 2, type: 'A', blade: 1, gun: 1, shield: 1, head: 1, body: 1, r_arm: 1, l_arm: 1, leg: 1, jump: 1, os: 1, assist: 0 },
    { id: 6, name: '長刀攻撃力エンハンサー', effect_limit: 20, parts_limit: 10, percent_flg: 1, add_flg: 1, group: 3, type: 'B', blade: 1, gun: 0, shield: 1, head: 1, body: 1, r_arm: 1, l_arm: 1, leg: 1, jump: 1, os: 0, assist: 1 },
    { id: 7, name: '突撃砲攻撃力エンハンサー', effect_limit: 20, parts_limit: 10, percent_flg: 1, add_flg: 1, group: 3, type: 'B', blade: 0, gun: 1, shield: 1, head: 1, body: 1, r_arm: 1, l_arm: 1, leg: 1, jump: 1, os: 0, assist: 1 },
    { id: 8, name: '格闘攻撃力エンハンサー', effect_limit: 20, parts_limit: 10, percent_flg: 1, add_flg: 1, group: 3, type: 'B', blade: 1, gun: 1, shield: 0, head: 1, body: 1, r_arm: 1, l_arm: 1, leg: 1, jump: 1, os: 0, assist: 1 },
    { id: 9, name: '追加装甲攻撃力エンハンサー', effect_limit: 20, parts_limit: 10, percent_flg: 1, add_flg: 1, group: 3, type: 'B', blade: 1, gun: 1, shield: 1, head: 1, body: 1, r_arm: 1, l_arm: 1, leg: 1, jump: 1, os: 0, assist: 1 },
    { id: 10, name: '防御力プラス', effect_limit: 999, parts_limit: 250, percent_flg: 0, add_flg: 0, group: 4, type: 'A', blade: 0, gun: 0, shield: 1, head: 1, body: 1, r_arm: 1, l_arm: 1, leg: 1, jump: 1, os: 0, assist: 0 },
    { id: 11, name: '頭部防御力アップ', effect_limit: 25, parts_limit: 15, percent_flg: 1, add_flg: 1, group: 5, type: 'A', blade: 1, gun: 1, shield: 1, head: 1, body: 1, r_arm: 1, l_arm: 1, leg: 1, jump: 1, os: 1, assist: 0 },
    { id: 12, name: '胸部防御力アップ', effect_limit: 25, parts_limit: 15, percent_flg: 1, add_flg: 1, group: 5, type: 'A', blade: 1, gun: 1, shield: 1, head: 1, body: 1, r_arm: 1, l_arm: 1, leg: 1, jump: 1, os: 1, assist: 0 },
    { id: 13, name: '右主腕防御力アップ', effect_limit: 25, parts_limit: 15, percent_flg: 1, add_flg: 1, group: 5, type: 'A', blade: 1, gun: 1, shield: 1, head: 1, body: 1, r_arm: 1, l_arm: 1, leg: 1, jump: 1, os: 1, assist: 0 },
    { id: 14, name: '左主腕防御力アップ', effect_limit: 25, parts_limit: 15, percent_flg: 1, add_flg: 1, group: 5, type: 'A', blade: 1, gun: 1, shield: 1, head: 1, body: 1, r_arm: 1, l_arm: 1, leg: 1, jump: 1, os: 1, assist: 0 },
    { id: 15, name: '主脚防御力アップ', effect_limit: 25, parts_limit: 15, percent_flg: 1, add_flg: 1, group: 5, type: 'A', blade: 1, gun: 1, shield: 1, head: 1, body: 1, r_arm: 1, l_arm: 1, leg: 1, jump: 1, os: 1, assist: 0 },
    { id: 16, name: '跳躍ユニット防御力アップ', effect_limit: 25, parts_limit: 15, percent_flg: 1, add_flg: 1, group: 5, type: 'A', blade: 1, gun: 1, shield: 1, head: 1, body: 1, r_arm: 1, l_arm: 1, leg: 1, jump: 1, os: 1, assist: 0 },
    { id: 17, name: '追加装甲防御力アップ', effect_limit: 25, parts_limit: 15, percent_flg: 1, add_flg: 1, group: 5, type: 'A', blade: 1, gun: 1, shield: 1, head: 1, body: 1, r_arm: 1, l_arm: 1, leg: 1, jump: 1, os: 1, assist: 0 },
    { id: 18, name: '頭部防御力エンハンサー', effect_limit: 20, parts_limit: 10, percent_flg: 1, add_flg: 1, group: 6, type: 'B', blade: 1, gun: 1, shield: 1, head: 1, body: 1, r_arm: 0, l_arm: 0, leg: 1, jump: 1, os: 0, assist: 1 },
    { id: 19, name: '胸部防御力エンハンサー', effect_limit: 20, parts_limit: 10, percent_flg: 1, add_flg: 1, group: 6, type: 'B', blade: 1, gun: 1, shield: 1, head: 1, body: 1, r_arm: 0, l_arm: 0, leg: 1, jump: 1, os: 0, assist: 1 },
    { id: 20, name: '右主腕防御力エンハンサー', effect_limit: 20, parts_limit: 10, percent_flg: 1, add_flg: 1, group: 6, type: 'B', blade: 1, gun: 1, shield: 1, head: 1, body: 1, r_arm: 1, l_arm: 0, leg: 1, jump: 1, os: 0, assist: 1 },
    { id: 21, name: '左主腕防御力エンハンサー', effect_limit: 20, parts_limit: 10, percent_flg: 1, add_flg: 1, group: 6, type: 'B', blade: 1, gun: 1, shield: 1, head: 1, body: 1, r_arm: 0, l_arm: 1, leg: 1, jump: 1, os: 0, assist: 1 },
    { id: 22, name: '主脚防御力エンハンサー', effect_limit: 20, parts_limit: 10, percent_flg: 1, add_flg: 1, group: 6, type: 'B', blade: 1, gun: 1, shield: 1, head: 1, body: 1, r_arm: 0, l_arm: 0, leg: 1, jump: 1, os: 0, assist: 1 },
    { id: 23, name: '跳躍ユニット防御力エンハンサー', effect_limit: 20, parts_limit: 10, percent_flg: 1, add_flg: 1, group: 6, type: 'B', blade: 1, gun: 1, shield: 1, head: 1, body: 1, r_arm: 0, l_arm: 0, leg: 1, jump: 1, os: 0, assist: 1 },
    { id: 24, name: '追加装甲防御力エンハンサー', effect_limit: 20, parts_limit: 10, percent_flg: 1, add_flg: 1, group: 6, type: 'B', blade: 1, gun: 1, shield: 1, head: 1, body: 1, r_arm: 0, l_arm: 0, leg: 1, jump: 1, os: 0, assist: 1 },
    { id: 25, name: '生命力回復量アップ', effect_limit: 50, parts_limit: 36, percent_flg: 1, add_flg: 1, group: 7, type: 'B', blade: 1, gun: 1, shield: 1, head: 1, body: 1, r_arm: 1, l_arm: 1, leg: 1, jump: 1, os: 0, assist: 1 },
    { id: 26, name: '生命力回復ウェイト短縮', effect_limit: 50, parts_limit: 36, percent_flg: 1, add_flg: 1, group: 7, type: 'A', blade: 1, gun: 1, shield: 1, head: 1, body: 1, r_arm: 1, l_arm: 1, leg: 1, jump: 1, os: 1, assist: 0 },
    { id: 27, name: '機動性能アップ', effect_limit: 20, parts_limit: 20, percent_flg: 1, add_flg: 0, group: 8, type: 'A', blade: 1, gun: 1, shield: 1, head: 1, body: 1, r_arm: 1, l_arm: 1, leg: 1, jump: 1, os: 1, assist: 0 },
    { id: 28, name: '巡航性能アップ', effect_limit: 50, parts_limit: 36, percent_flg: 1, add_flg: 1, group: 9, type: 'A', blade: 1, gun: 1, shield: 1, head: 1, body: 1, r_arm: 1, l_arm: 1, leg: 1, jump: 1, os: 1, assist: 0 },
    { id: 29, name: '滞空性能アップ', effect_limit: 50, parts_limit: 36, percent_flg: 1, add_flg: 1, group: 10, type: 'A', blade: 1, gun: 1, shield: 1, head: 1, body: 1, r_arm: 1, l_arm: 1, leg: 1, jump: 1, os: 1, assist: 0 },
    { id: 30, name: '跳躍システム負荷軽減', effect_limit: 50, parts_limit: 36, percent_flg: 1, add_flg: 1, group: 11, type: 'B', blade: 1, gun: 1, shield: 1, head: 1, body: 1, r_arm: 1, l_arm: 1, leg: 1, jump: 1, os: 0, assist: 1 },
    { id: 31, name: '跳躍システム回復性能アップ', effect_limit: 50, parts_limit: 36, percent_flg: 1, add_flg: 1, group: 11, type: 'B', blade: 1, gun: 1, shield: 1, head: 1, body: 1, r_arm: 1, l_arm: 1, leg: 1, jump: 1, os: 0, assist: 1 },
    { id: 32, name: '長刀クリティカル確率アップ', effect_limit: 50, parts_limit: 36, percent_flg: 1, add_flg: 1, group: 12, type: 'A', blade: 1, gun: 0, shield: 1, head: 1, body: 1, r_arm: 1, l_arm: 1, leg: 1, jump: 1, os: 1, assist: 0 },
    { id: 33, name: '突撃砲クリティカル確率アップ', effect_limit: 50, parts_limit: 36, percent_flg: 1, add_flg: 1, group: 12, type: 'A', blade: 0, gun: 1, shield: 1, head: 1, body: 1, r_arm: 1, l_arm: 1, leg: 1, jump: 1, os: 1, assist: 0 },
    { id: 34, name: '格闘クリティカル確率アップ', effect_limit: 50, parts_limit: 36, percent_flg: 1, add_flg: 1, group: 12, type: 'A', blade: 1, gun: 1, shield: 0, head: 1, body: 1, r_arm: 1, l_arm: 1, leg: 1, jump: 1, os: 1, assist: 0 },
    { id: 35, name: '追加装甲クリティカル確率アップ', effect_limit: 50, parts_limit: 36, percent_flg: 1, add_flg: 1, group: 12, type: 'A', blade: 1, gun: 1, shield: 1, head: 1, body: 1, r_arm: 1, l_arm: 1, leg: 1, jump: 1, os: 1, assist: 0 },
    { id: 36, name: '長刀クリティカルパワーアップ', effect_limit: 25, parts_limit: 15, percent_flg: 1, add_flg: 1, group: 13, type: 'A', blade: 1, gun: 0, shield: 1, head: 1, body: 1, r_arm: 1, l_arm: 1, leg: 1, jump: 1, os: 1, assist: 0 },
    { id: 37, name: '突撃砲クリティカルパワーアップ', effect_limit: 25, parts_limit: 15, percent_flg: 1, add_flg: 1, group: 13, type: 'A', blade: 0, gun: 1, shield: 1, head: 1, body: 1, r_arm: 1, l_arm: 1, leg: 1, jump: 1, os: 1, assist: 0 },
    { id: 38, name: '格闘クリティカルパワーアップ', effect_limit: 25, parts_limit: 15, percent_flg: 1, add_flg: 1, group: 13, type: 'A', blade: 1, gun: 1, shield: 0, head: 1, body: 1, r_arm: 1, l_arm: 1, leg: 1, jump: 1, os: 1, assist: 0 },
    { id: 39, name: '追加装甲クリティカルパワーアップ', effect_limit: 25, parts_limit: 15, percent_flg: 1, add_flg: 1, group: 13, type: 'A', blade: 1, gun: 1, shield: 1, head: 1, body: 1, r_arm: 1, l_arm: 1, leg: 1, jump: 1, os: 1, assist: 0 },
    { id: 40, name: 'クリティカルギャランティ', effect_limit: 8, parts_limit: 8, percent_flg: 1, add_flg: 0, group: 14, type: 'B', blade: 1, gun: 1, shield: 1, head: 1, body: 1, r_arm: 1, l_arm: 1, leg: 1, jump: 1, os: 0, assist: 1 },
    { id: 41, name: 'クリティカルパワーブースター', effect_limit: 8, parts_limit: 8, percent_flg: 1, add_flg: 0, group: 14, type: 'B', blade: 1, gun: 1, shield: 1, head: 1, body: 1, r_arm: 1, l_arm: 1, leg: 1, jump: 1, os: 0, assist: 1 },
    { id: 42, name: 'クリティカルデストロイ', effect_limit: 25, parts_limit: 15, percent_flg: 1, add_flg: 1, group: 14, type: 'B', blade: 1, gun: 1, shield: 1, head: 1, body: 1, r_arm: 1, l_arm: 1, leg: 1, jump: 1, os: 0, assist: 1 },
    { id: 43, name: 'フィニッシュブローマイスター', effect_limit: 25, parts_limit: 15, percent_flg: 1, add_flg: 1, group: 15, type: 'B', blade: 1, gun: 1, shield: 1, head: 1, body: 1, r_arm: 1, l_arm: 1, leg: 1, jump: 1, os: 0, assist: 1 },
    { id: 44, name: 'スマッシュヒッター', effect_limit: 1, parts_limit: 1, percent_flg: 0, add_flg: 0, group: 16, type: 'B', blade: 1, gun: 0, shield: 1, head: 1, body: 1, r_arm: 1, l_arm: 1, leg: 1, jump: 1, os: 0, assist: 1 },
    { id: 45, name: '36mm弾ダメージアップ', effect_limit: 20, parts_limit: 10, percent_flg: 1, add_flg: 1, group: 17, type: 'A', blade: 0, gun: 1, shield: 1, head: 0, body: 0, r_arm: 0, l_arm: 0, leg: 0, jump: 0, os: 1, assist: 0 },
    { id: 46, name: '120mm弾ダメージアップ', effect_limit: 20, parts_limit: 10, percent_flg: 1, add_flg: 1, group: 17, type: 'A', blade: 0, gun: 1, shield: 1, head: 0, body: 0, r_arm: 0, l_arm: 0, leg: 0, jump: 0, os: 0, assist: 0 },
    { id: 47, name: '36mm装弾数プラス', effect_limit: 10, parts_limit: 10, percent_flg: 0, add_flg: 0, group: 18, type: 'A', blade: 0, gun: 1, shield: 0, head: 0, body: 0, r_arm: 0, l_arm: 0, leg: 0, jump: 0, os: 0, assist: 0 },
    { id: 48, name: '120mm装弾数プラス', effect_limit: 6, parts_limit: 6, percent_flg: 0, add_flg: 0, group: 18, type: 'A', blade: 0, gun: 1, shield: 0, head: 0, body: 0, r_arm: 0, l_arm: 0, leg: 0, jump: 0, os: 0, assist: 0 },
    { id: 49, name: '再装填制限時間短縮', effect_limit: 25, parts_limit: 15, percent_flg: 1, add_flg: 1, group: 19, type: 'B', blade: 0, gun: 1, shield: 1, head: 1, body: 1, r_arm: 1, l_arm: 1, leg: 1, jump: 1, os: 0, assist: 1 },
    { id: 50, name: '連射性能プラス', effect_limit: 10, parts_limit: 10, percent_flg: 1, add_flg: 0, group: 20, type: 'A', blade: 0, gun: 1, shield: 0, head: 0, body: 0, r_arm: 0, l_arm: 0, leg: 0, jump: 0, os: 0, assist: 0 },
    { id: 51, name: '連射性能エンハンサー', effect_limit: 20, parts_limit: 10, percent_flg: 1, add_flg: 1, group: 20, type: 'B', blade: 0, gun: 1, shield: 1, head: 1, body: 1, r_arm: 1, l_arm: 1, leg: 1, jump: 1, os: 0, assist: 1 },
    { id: 52, name: 'トリガーハッピー', effect_limit: 4, parts_limit: 4, percent_flg: 1, add_flg: 0, group: 21, type: 'B', blade: 0, gun: 1, shield: 1, head: 1, body: 1, r_arm: 1, l_arm: 1, leg: 1, jump: 1, os: 0, assist: 1 },
    { id: 53, name: '火事場力', effect_limit: 40, parts_limit: 40, percent_flg: 1, add_flg: 0, group: 22, type: 'B', blade: 1, gun: 0, shield: 1, head: 1, body: 1, r_arm: 1, l_arm: 1, leg: 1, jump: 1, os: 0, assist: 1 },
    { id: 54, name: '破壊力アップ', effect_limit: 25, parts_limit: 15, percent_flg: 1, add_flg: 1, group: 23, type: 'A', blade: 1, gun: 1, shield: 1, head: 1, body: 1, r_arm: 1, l_arm: 1, leg: 1, jump: 1, os: 1, assist: 0 },
    { id: 55, name: '斬撃シールド', effect_limit: 25, parts_limit: 15, percent_flg: 1, add_flg: 1, group: 24, type: 'B', blade: 1, gun: 1, shield: 1, head: 1, body: 1, r_arm: 1, l_arm: 1, leg: 1, jump: 1, os: 0, assist: 1 },
    { id: 56, name: '刺撃シールド', effect_limit: 25, parts_limit: 15, percent_flg: 1, add_flg: 1, group: 24, type: 'B', blade: 1, gun: 1, shield: 1, head: 1, body: 1, r_arm: 1, l_arm: 1, leg: 1, jump: 1, os: 0, assist: 1 },
    { id: 57, name: '衝撃シールド', effect_limit: 25, parts_limit: 15, percent_flg: 1, add_flg: 1, group: 24, type: 'B', blade: 1, gun: 1, shield: 1, head: 1, body: 1, r_arm: 1, l_arm: 1, leg: 1, jump: 1, os: 0, assist: 1 },
    { id: 58, name: '光線シールド', effect_limit: 25, parts_limit: 15, percent_flg: 1, add_flg: 1, group: 24, type: 'B', blade: 1, gun: 1, shield: 1, head: 1, body: 1, r_arm: 1, l_arm: 1, leg: 1, jump: 1, os: 0, assist: 1 },
    { id: 59, name: 'ガード性能アップ', effect_limit: 3, parts_limit: 1, percent_flg: 0, add_flg: 1, group: 25, type: 'A', blade: 1, gun: 1, shield: 1, head: 1, body: 1, r_arm: 1, l_arm: 1, leg: 1, jump: 1, os: 1, assist: 0 },
    { id: 60, name: 'イージードッジ', effect_limit: 4, parts_limit: 4, percent_flg: 0, add_flg: 1, group: 26, type: 'B', blade: 1, gun: 1, shield: 0, head: 1, body: 1, r_arm: 1, l_arm: 1, leg: 1, jump: 1, os: 0, assist: 1 },
    { id: 61, name: 'エクストラドッジタイムプラス', effect_limit: 50, parts_limit: 36, percent_flg: 1, add_flg: 1, group: 26, type: 'B', blade: 1, gun: 1, shield: 0, head: 1, body: 1, r_arm: 1, l_arm: 1, leg: 1, jump: 1, os: 0, assist: 1 },
    { id: 62, name: 'イージーガード', effect_limit: 4, parts_limit: 4, percent_flg: 0, add_flg: 1, group: 26, type: 'B', blade: 1, gun: 1, shield: 1, head: 1, body: 1, r_arm: 1, l_arm: 1, leg: 1, jump: 1, os: 0, assist: 1 },
    { id: 63, name: 'ジャストガード性能アップ', effect_limit: 25, parts_limit: 15, percent_flg: 1, add_flg: 1, group: 27, type: 'A', blade: 1, gun: 1, shield: 1, head: 1, body: 1, r_arm: 1, l_arm: 1, leg: 1, jump: 1, os: 1, assist: 0 },
    { id: 64, name: 'ブロッキング性能アップ', effect_limit: 25, parts_limit: 15, percent_flg: 1, add_flg: 1, group: 27, type: 'A', blade: 1, gun: 0, shield: 1, head: 1, body: 1, r_arm: 1, l_arm: 1, leg: 1, jump: 1, os: 1, assist: 0 },
    { id: 65, name: 'クリティカルリデューサー', effect_limit: 25, parts_limit: 15, percent_flg: 1, add_flg: 1, group: 28, type: 'A', blade: 1, gun: 1, shield: 1, head: 1, body: 1, r_arm: 1, l_arm: 1, leg: 1, jump: 1, os: 1, assist: 0 },
    { id: 66, name: 'クリティカルディフェンダー', effect_limit: 25, parts_limit: 15, percent_flg: 1, add_flg: 1, group: 28, type: 'A', blade: 1, gun: 1, shield: 1, head: 1, body: 1, r_arm: 1, l_arm: 1, leg: 1, jump: 1, os: 1, assist: 0 },
    { id: 67, name: '九死に一生を得る', effect_limit: 30, parts_limit: 30, percent_flg: 1, add_flg: 0, group: 29, type: 'B', blade: 1, gun: 1, shield: 1, head: 1, body: 1, r_arm: 1, l_arm: 1, leg: 1, jump: 1, os: 0, assist: 1 },
    { id: 68, name: '破壊レジスタンス', effect_limit: 80, parts_limit: 35, percent_flg: 1, add_flg: 1, group: 30, type: 'A', blade: 1, gun: 1, shield: 1, head: 1, body: 1, r_arm: 1, l_arm: 1, leg: 1, jump: 1, os: 1, assist: 0 },
    { id: 69, name: 'ドロップカウントブースト', effect_limit: 15, parts_limit: 15, percent_flg: 1, add_flg: 0, group: 31, type: 'A', blade: 0, gun: 0, shield: 0, head: 0, body: 0, r_arm: 0, l_arm: 0, leg: 0, jump: 0, os: 1, assist: 0 },
    { id: 70, name: '熟練エクスペリエンスブースト', effect_limit: 15, parts_limit: 15, percent_flg: 1, add_flg: 0, group: 32, type: 'A', blade: 0, gun: 0, shield: 0, head: 0, body: 0, r_arm: 0, l_arm: 0, leg: 0, jump: 0, os: 1, assist: 0 },
    { id: 71, name: '長刀攻撃スピードアップ', effect_limit: 20, parts_limit: 20, percent_flg: 1, add_flg: 0, group: 33, type: 'A', blade: 1, gun: 0, shield: 1, head: 0, body: 0, r_arm: 0, l_arm: 0, leg: 0, jump: 0, os: 1, assist: 0 },
    { id: 72, name: '格闘攻撃スピードアップ', effect_limit: 20, parts_limit: 20, percent_flg: 1, add_flg: 0, group: 33, type: 'A', blade: 1, gun: 1, shield: 0, head: 0, body: 0, r_arm: 1, l_arm: 1, leg: 0, jump: 0, os: 1, assist: 0 },
    { id: 73, name: 'スキルチャージアップ', effect_limit: 20, parts_limit: 20, percent_flg: 1, add_flg: 0, group: 34, type: 'B', blade: 1, gun: 1, shield: 1, head: 1, body: 1, r_arm: 1, l_arm: 1, leg: 1, jump: 1, os: 0, assist: 1 },
    { id: 74, name: '戦車級キラー', effect_limit: 20, parts_limit: 15, percent_flg: 1, add_flg: 1, group: 35, type: 'B', blade: 1, gun: 1, shield: 1, head: 0, body: 0, r_arm: 1, l_arm: 1, leg: 0, jump: 0, os: 0, assist: 1 },
    { id: 75, name: '光線級キラー', effect_limit: 20, parts_limit: 15, percent_flg: 1, add_flg: 1, group: 35, type: 'B', blade: 1, gun: 1, shield: 1, head: 0, body: 0, r_arm: 1, l_arm: 1, leg: 0, jump: 0, os: 0, assist: 1 },
    { id: 76, name: '要撃級キラー', effect_limit: 20, parts_limit: 15, percent_flg: 1, add_flg: 1, group: 35, type: 'B', blade: 1, gun: 1, shield: 1, head: 0, body: 0, r_arm: 1, l_arm: 1, leg: 0, jump: 0, os: 0, assist: 1 },
    { id: 77, name: '突撃級キラー', effect_limit: 20, parts_limit: 15, percent_flg: 1, add_flg: 1, group: 35, type: 'B', blade: 1, gun: 1, shield: 1, head: 0, body: 0, r_arm: 1, l_arm: 1, leg: 0, jump: 0, os: 0, assist: 1 },
    { id: 78, name: '重光線級キラー', effect_limit: 20, parts_limit: 15, percent_flg: 1, add_flg: 1, group: 35, type: 'B', blade: 1, gun: 1, shield: 1, head: 0, body: 0, r_arm: 1, l_arm: 1, leg: 0, jump: 0, os: 0, assist: 1 },
    { id: 79, name: '要塞級キラー', effect_limit: 20, parts_limit: 15, percent_flg: 1, add_flg: 1, group: 35, type: 'B', blade: 1, gun: 1, shield: 1, head: 0, body: 0, r_arm: 1, l_arm: 1, leg: 0, jump: 0, os: 0, assist: 1 },
    { id: 80, name: '戦術機キラー', effect_limit: 20, parts_limit: 15, percent_flg: 1, add_flg: 1, group: 35, type: 'B', blade: 1, gun: 1, shield: 1, head: 0, body: 0, r_arm: 1, l_arm: 1, leg: 0, jump: 0, os: 0, assist: 1 },
    { id: 81, name: 'スキルポイントアップ', effect_limit: 15, parts_limit: 15, percent_flg: 1, add_flg: 0, group: 0, type: 'C', blade: 0, gun: 0, shield: 0, head: 0, body: 0, r_arm: 0, l_arm: 0, leg: 0, jump: 0, os: 0, assist: 0 },
    { id: 82, name: 'HP50%以上ダメージ一撃', effect_limit: 1, parts_limit: 1, percent_flg: 0, add_flg: 0, group: 0, type: 'C', blade: 0, gun: 0, shield: 0, head: 0, body: 0, r_arm: 0, l_arm: 0, leg: 0, jump: 0, os: 0, assist: 0 },
];

var master_parts_list = [
    { id: 0, text: 'パーツを選択してください', value: 'nodata'},
    { id: 1, text: '74式近接戦闘長刀', value: 'blade'},
    { id: 2, text: '77式近接戦闘長刀', value: 'blade'},
    { id: 3, text: '82式突撃砲【APCBCHE】', value: 'gun'},
    { id: 4, text: '87式突撃砲【APCBCHE】', value: 'gun'},
    { id: 5, text: 'AMWS-21【APCBCHE】', value: 'gun'},
    { id: 6, text: 'WS-16C【APCBCHE】', value: 'gun'},
    { id: 7, text: '82式突撃砲【APFSDS】', value: 'gun'},
    { id: 8, text: '87式突撃砲【APFSDS】', value: 'gun'},
    { id: 9, text: 'AMWS-21【APFSDS】', value: 'gun'},
    { id: 10, text: 'WS-16C【APFSDS】', value: 'gun'},
    { id: 11, text: '87式支援突撃砲', value: 'gun'},
    { id: 12, text: '92式多目的追加装甲', value: 'shield'},
    { id: 13, text: '基礎機体制御', value: 'os'},
    { id: 14, text: '損耗軽減ルーチン', value: 'os'},
    { id: 15, text: '兵装管理高速処理', value: 'os'},
    { id: 16, text: 'Type OBW', value: 'assist'},
    { id: 17, text: 'Type OBWL', value: 'assist'},
    { id: 18, text: 'Type OBL', value: 'assist'},
    { id: 19, text: '撃震', value: 'head'},
    { id: 20, text: '瑞鶴', value: 'head'},
    { id: 21, text: '陽炎', value: 'head'},
    { id: 22, text: '陽炎【国連】', value: 'head'},
    { id: 23, text: '吹雪', value: 'head'},
    { id: 24, text: '吹雪【国連】', value: 'head'},
    { id: 25, text: '不知火', value: 'head'},
    { id: 26, text: '不知火【国連】', value: 'head'},
    { id: 27, text: '不知火【富士教導隊】', value: 'head'},
    { id: 28, text: '武御雷【標準】', value: 'head'},
    { id: 29, text: '武御雷【外様武家】', value: 'head'},
    { id: 30, text: '武御雷【親藩武家】', value: 'head'},
    { id: 31, text: '武御雷【征夷大将軍】', value: 'head'},
    { id: 32, text: 'ファントム', value: 'head'},
    { id: 33, text: 'トムキャット', value: 'head'},
    { id: 34, text: 'イーグル', value: 'head'},
    { id: 35, text: 'ストライク・イーグル', value: 'head'},
    { id: 36, text: 'ラプター', value: 'head'},
    { id: 37, text: 'ブラックウィドウⅡ', value: 'head'},
    { id: 38, text: 'バラライカ', value: 'head'},
    { id: 39, text: 'チボラシュカ', value: 'head'},
    { id: 40, text: 'アリゲートル', value: 'head'},
    { id: 41, text: 'ジュラーブリク', value: 'head'},
    { id: 42, text: 'チェルミナートル', value: 'head'},
    { id: 43, text: '殲撃8型', value: 'head'},
    { id: 44, text: '撃震', value: 'body'},
    { id: 45, text: '瑞鶴', value: 'body'},
    { id: 46, text: '陽炎', value: 'body'},
    { id: 47, text: '陽炎【国連】', value: 'body'},
    { id: 48, text: '吹雪', value: 'body'},
    { id: 49, text: '吹雪【国連】', value: 'body'},
    { id: 50, text: '不知火', value: 'body'},
    { id: 51, text: '不知火【国連】', value: 'body'},
    { id: 52, text: '不知火【富士教導隊】', value: 'body'},
    { id: 53, text: '武御雷【標準】', value: 'body'},
    { id: 54, text: '武御雷【外様武家】', value: 'body'},
    { id: 55, text: '武御雷【親藩武家】', value: 'body'},
    { id: 56, text: '武御雷【征夷大将軍】', value: 'body'},
    { id: 57, text: 'ファントム', value: 'body'},
    { id: 58, text: 'トムキャット', value: 'body'},
    { id: 59, text: 'イーグル', value: 'body'},
    { id: 60, text: 'ストライク・イーグル', value: 'body'},
    { id: 61, text: 'ラプター', value: 'body'},
    { id: 62, text: 'ブラックウィドウⅡ', value: 'body'},
    { id: 63, text: 'バラライカ', value: 'body'},
    { id: 64, text: 'チボラシュカ', value: 'body'},
    { id: 65, text: 'アリゲートル', value: 'body'},
    { id: 66, text: 'ジュラーブリク', value: 'body'},
    { id: 67, text: 'チェルミナートル', value: 'body'},
    { id: 68, text: '殲撃8型', value: 'body'},
    { id: 69, text: '撃震', value: 'r_arm'},
    { id: 70, text: '瑞鶴', value: 'r_arm'},
    { id: 71, text: '陽炎', value: 'r_arm'},
    { id: 72, text: '陽炎【国連】', value: 'r_arm'},
    { id: 73, text: '吹雪', value: 'r_arm'},
    { id: 74, text: '吹雪【国連】', value: 'r_arm'},
    { id: 75, text: '不知火', value: 'r_arm'},
    { id: 76, text: '不知火【国連】', value: 'r_arm'},
    { id: 77, text: '不知火【富士教導隊】', value: 'r_arm'},
    { id: 78, text: '武御雷【標準】', value: 'r_arm'},
    { id: 79, text: '武御雷【外様武家】', value: 'r_arm'},
    { id: 80, text: '武御雷【親藩武家】', value: 'r_arm'},
    { id: 81, text: '武御雷【征夷大将軍】', value: 'r_arm'},
    { id: 82, text: 'ファントム', value: 'r_arm'},
    { id: 83, text: 'トムキャット', value: 'r_arm'},
    { id: 84, text: 'イーグル', value: 'r_arm'},
    { id: 85, text: 'ストライク・イーグル', value: 'r_arm'},
    { id: 86, text: 'ラプター', value: 'r_arm'},
    { id: 87, text: 'ブラックウィドウⅡ', value: 'r_arm'},
    { id: 88, text: 'バラライカ', value: 'r_arm'},
    { id: 89, text: 'チボラシュカ', value: 'r_arm'},
    { id: 90, text: 'アリゲートル', value: 'r_arm'},
    { id: 91, text: 'ジュラーブリク', value: 'r_arm'},
    { id: 92, text: 'チェルミナートル', value: 'r_arm'},
    { id: 93, text: '殲撃8型', value: 'r_arm'},
    { id: 94, text: '撃震', value: 'l_arm'},
    { id: 95, text: '瑞鶴', value: 'l_arm'},
    { id: 96, text: '陽炎', value: 'l_arm'},
    { id: 97, text: '陽炎【国連】', value: 'l_arm'},
    { id: 98, text: '吹雪', value: 'l_arm'},
    { id: 99, text: '吹雪【国連】', value: 'l_arm'},
    { id: 100, text: '不知火', value: 'l_arm'},
    { id: 101, text: '不知火【国連】', value: 'l_arm'},
    { id: 102, text: '不知火【富士教導隊】', value: 'l_arm'},
    { id: 103, text: '武御雷【標準】', value: 'l_arm'},
    { id: 104, text: '武御雷【外様武家】', value: 'l_arm'},
    { id: 105, text: '武御雷【親藩武家】', value: 'l_arm'},
    { id: 106, text: '武御雷【征夷大将軍】', value: 'l_arm'},
    { id: 107, text: 'ファントム', value: 'l_arm'},
    { id: 108, text: 'トムキャット', value: 'l_arm'},
    { id: 109, text: 'イーグル', value: 'l_arm'},
    { id: 110, text: 'ストライク・イーグル', value: 'l_arm'},
    { id: 111, text: 'ラプター', value: 'l_arm'},
    { id: 112, text: 'ブラックウィドウⅡ', value: 'l_arm'},
    { id: 113, text: 'バラライカ', value: 'l_arm'},
    { id: 114, text: 'チボラシュカ', value: 'l_arm'},
    { id: 115, text: 'アリゲートル', value: 'l_arm'},
    { id: 116, text: 'ジュラーブリク', value: 'l_arm'},
    { id: 117, text: 'チェルミナートル', value: 'l_arm'},
    { id: 118, text: '殲撃8型', value: 'l_arm'},
    { id: 119, text: '撃震', value: 'leg'},
    { id: 120, text: '瑞鶴', value: 'leg'},
    { id: 121, text: '陽炎', value: 'leg'},
    { id: 122, text: '陽炎【国連】', value: 'leg'},
    { id: 123, text: '吹雪', value: 'leg'},
    { id: 124, text: '吹雪【国連】', value: 'leg'},
    { id: 125, text: '不知火', value: 'leg'},
    { id: 126, text: '不知火【国連】', value: 'leg'},
    { id: 127, text: '不知火【富士教導隊】', value: 'leg'},
    { id: 128, text: '武御雷【標準】', value: 'leg'},
    { id: 129, text: '武御雷【外様武家】', value: 'leg'},
    { id: 130, text: '武御雷【親藩武家】', value: 'leg'},
    { id: 131, text: '武御雷【征夷大将軍】', value: 'leg'},
    { id: 132, text: 'ファントム', value: 'leg'},
    { id: 133, text: 'トムキャット', value: 'leg'},
    { id: 134, text: 'イーグル', value: 'leg'},
    { id: 135, text: 'ストライク・イーグル', value: 'leg'},
    { id: 136, text: 'ラプター', value: 'leg'},
    { id: 137, text: 'ブラックウィドウⅡ', value: 'leg'},
    { id: 138, text: 'バラライカ', value: 'leg'},
    { id: 139, text: 'チボラシュカ', value: 'leg'},
    { id: 140, text: 'アリゲートル', value: 'leg'},
    { id: 141, text: 'ジュラーブリク', value: 'leg'},
    { id: 142, text: 'チェルミナートル', value: 'leg'},
    { id: 143, text: '殲撃8型', value: 'leg'},
    { id: 144, text: '撃震', value: 'jump'},
    { id: 145, text: '瑞鶴', value: 'jump'},
    { id: 146, text: '陽炎', value: 'jump'},
    { id: 147, text: '陽炎【国連】', value: 'jump'},
    { id: 148, text: '吹雪', value: 'jump'},
    { id: 149, text: '吹雪【国連】', value: 'jump'},
    { id: 150, text: '不知火', value: 'jump'},
    { id: 151, text: '不知火【国連】', value: 'jump'},
    { id: 152, text: '不知火【富士教導隊】', value: 'jump'},
    { id: 153, text: '武御雷【標準】', value: 'jump'},
    { id: 154, text: '武御雷【外様武家】', value: 'jump'},
    { id: 155, text: '武御雷【親藩武家】', value: 'jump'},
    { id: 156, text: '武御雷【征夷大将軍】', value: 'jump'},
    { id: 157, text: 'ファントム', value: 'jump'},
    { id: 158, text: 'トムキャット', value: 'jump'},
    { id: 159, text: 'イーグル', value: 'jump'},
    { id: 160, text: 'ストライク・イーグル', value: 'jump'},
    { id: 161, text: 'ラプター', value: 'jump'},
    { id: 162, text: 'ブラックウィドウⅡ', value: 'jump'},
    { id: 163, text: 'バラライカ', value: 'jump'},
    { id: 164, text: 'チボラシュカ', value: 'jump'},
    { id: 165, text: 'アリゲートル', value: 'jump'},
    { id: 166, text: 'ジュラーブリク', value: 'jump'},
    { id: 167, text: 'チェルミナートル', value: 'jump'},
    { id: 168, text: '殲撃8型', value: 'jump'}
];

function parts_load(element) {
    let s_parts_id;
    let e_parts_id;

    switch(element) {
        case 'main':
        case 'sub':
        case 'r_spare':
        case 'l_spare':
            s_parts_id = 1;
            e_parts_id = 12;
            break;

        default:
            s_parts_id = -1;
            break;
    }

    for(i = 0 ; i < master_parts_list.length ; i++) {
        if(s_parts_id == -1 && master_parts_list[i].value == element || i >= s_parts_id && i <= e_parts_id) {
            let add_select = document.createElement('option');
            add_select.value = master_parts_list[i].id;
            add_select.textContent = master_parts_list[i].text;
        
            document.getElementById(element).appendChild(add_select);
        }
    }
}